[tool.isort]
profile = "black"
multi_line_output = 3

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38

[testenv]
deps =
    pytest
    pytest-cov

commands = pytest --ignore=integration --cov=./ --cov-report=xml
"""
